### ISSUE TITLE
Mode to not scrobble at all

### ISSUE THREAD

**Issue by hugovk** [stephanebruckert/ShazamScrobbler#17]
Thanks for ShazamScrobbler, it seems really useful!

Probably more of an enhancement than a bug report.
1. Uncheck "Enable scrobbling"
2. Listen to some music so Shazam detects it
   -> It's shown in ShazamScrobbler, but with no Last.fm logo next to it
3. Stop playing the music.
4. Check "Enable scrobbling (1 songs awaiting)"

Actual result:
Track is scrobbled.

Expected result:
Track not scrobbled.

At least personally, I would like the option of being able to use Shazam for recognising songs but not want then scrobbled. I know I can quit ShazamScrobbler, and then reopen it later, but it'd be more convenient to be able to just switch scrobbling enabled/disabled from the application. (I'd probably forget to re-open it afterwards.)

I suppose the current enable/disable option is more of an online/offline option. I can see the benefit of this too, but being able to set it to just ignore tracks for a while would be great.

What do you think?

Thanks!

**Comment by stephanebruckert** [comment]
> I know I can quit ShazamScrobbler

 you meant Shazam?

Right now all tagged songs are (sooner or later) scrobbled. So you want Scrobbling to be dissociated from Tagging and I agree with you.

Here is a suggestion. Let's add this step to your existing scenario:

`5.`  Open a pop up asking the user if he wants to scrobble the last `x` queued items. Choices: `yes`, `no`, `cancel`.

Additionally, I will add the ability to remove scrobbled/unscrobbled items one by one.

**Comment by hugovk** [comment]
No, I meant ShazamScrobbler. In this case I'd keep Shazam open to see what the songs are, but not want to scrobble them. 
- For example, perhaps when watching a film, I want to know what they are, but not scrobble.
- But when listening to the radio, I want to know what they are and scrobble.

> 1. Open a pop up asking the user if he wants to scrobble the last x queued items. Choices: yes, no, cancel.

I'm not so keen on that, I'd find that a bit more work having to inspect a list and decide, one by one, do I want it scrobbled or not: "This one? Yes. That one? Yes. That one? Erm, yes, that too. That one? No, not that. Nor that. This one? ..." 

I find it easier, perceptually, to know that all will be scrobbled during a bit of time: "Scrobbling is on! All may pass!" And then turn it off: "Don't worry, none of the rubbish songs from this film will be scrobbled."

> Additionally, I will add the ability to remove scrobbled/unscrobbled items one by one.

That'd be good too, to be able to do quick fixups. (Warning: I think the Last.fm API call for unscrobble is  broken at the moment.)
