### ISSUE TITLE
Mavericks support?

### ISSUE THREAD

**Issue by keikoro** [stephanebruckert/ShazamScrobbler#27]
Heya, you're not planning to make the app backwards-compatible with Mavericks, are you? I'm asking because that's (10.9.5., to be more precise) what I'm still using on the machine I listen to internet streams from.

I could get the most current version of ShazamScrobbler installed without problems, it also recognises songs (! they are listed as queued now), but none of the elements in the login window show up (i.e. it's just a 'blank' grey window, no input fields for user/pass, no logo), so I can't actually scrobble the tracks.

**Comment by stephanebruckert** [comment]
Thanks for sharing this issue. Well that wasn't a plan until now! I just need to find a Mavericks machine to start investigating on this. If not I might attempt some fixes on a branch and ask you to build and try whether it works. Would you be up to help me this way?
And one question for now: is the "About" window currently being rendered properly?

**Comment by keikoro** [comment]
Sure I'd be up for helping/testing! (: (And more regularly available for that from March/mid-March on, until then quite busy with stuff so might not have time immediately.)

I've never worked on OS X projects (I guess the code is Objective C?) but know Xcode basics, so can build & try out stuff. I also have a machine with Yosemite installed so could change around things on my end too and see if they work on both machines. (Proper testing with Xcode... I'd need to read up on.)

And yup, the "About" window shows up fine on Mavericks!

**Comment by stephanebruckert** [comment]
Hi Kerstin, I haven't been able to find a Mavericks machine. I labeled the issue as "wontfix" until I find myself in a good environment to test this.

**Comment by keikoro** [comment]
Aww, too bad. I actually tried looking at the code but had trouble orientating myself having never worked on OS X projects. (My iOS knowledge definitely helped some, but wasn't enough. ^^)
