### ISSUE TITLE
Question: how to clear the queue?

### ISSUE THREAD

**Issue by hugovk** [stephanebruckert/ShazamScrobbler#28]
The menu says "Enable scrobbling (108 songs awaiting)".

I'd like to enable scrobbling whilst listening to a CD, but don't want it to scrobble all those songs from TV it picked up.

As online/offline mode https://github.com/stephanebruckert/ShazamScrobbler/issues/17 isn't implemented, is there a way to clear the whole queue?

If I just let it scrobble them all, it'd be difficult and take a long time to go back through my Last.fm profile to try and find them and delete them one by one. 

Thank you!

**Comment by stephanebruckert** [comment]
This is something I need too. I will have a thought about it and come back to you with a proper solution.

**Comment by marcus604** [comment]
Ran into this same issue, at least as a hack solution you can quit out of shazam and delete the folder containing the Shazam database.

`~/Library/Group Containers/4GWDBCF5A4.group.com.shazam/`

Launch shazam again and it re-creates the folder.
