### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by dacmail** [stephanebruckert/ShazamScrobbler#3]
Hi, can you tell me how to run this app in Mac OS X?

**Comment by henrikakselsen** [comment]
Same here, some instructions would be good. Is the plan just to do your own build in Xcode? Maybe you could add a binary to the repo?

**Comment by jowie** [comment]
I've done an Xcode build, and it gives me a menu in the menu bar with a star icon (★). The window it opens doesn't contain anything.

<img width="314" alt="screen shot 2015-08-25 at 13 38 33" src="https://cloud.githubusercontent.com/assets/176042/9466698/9f7d8cc8-4b2e-11e5-9516-ec5e8f4dd7e5.png">

**Comment by stephanebruckert** [comment]
This is the normal behavior as it's in development. I'm starting to have more time now. I will look into the completion of the UI and release a proper binary very soon.

**Comment by buremba** [comment]
+1

**Comment by stephanebruckert** [comment]
I am happy to announce the very first release of the ShazamScrobbler. You will find the .dmg file [in the release section](https://github.com/stephanebruckert/ShazamScrobbler/releases).
I am waiting for your feedbacks.

**Comment by hugovk** [comment]
@stephanebruckert Looks like you can close this now [binaries are available](https://github.com/stephanebruckert/ShazamScrobbler/releases) and [installation instructions are given](https://github.com/stephanebruckert/ShazamScrobbler#installation). :cake:

**Comment by stephanebruckert** [comment]
Thank you @hugovk
