### ISSUE TITLE
Not scrobbling

### ISSUE THREAD

**Issue by brlo1973** [stephanebruckert/ShazamScrobbler#31]
I'm using version 1.2.1 with Shazam 1.2.0 on Mac OSX Sierra.
App appears to be pulling data from Shazam and interacting with Last FM (in that scrobbles show in-app with usual red or grey circles alongside)
But when I check my profile on Last.FM, the tracks listed in ShazamScrobbler aren't there.
I should mention that I have this exact problem with another 3rd party scrobbler on my iPhone. 
In both cases, the tracks appear to have been scrobbled because the apps indicate successful output, and some interaction with Last.FM looks like it has been achieved. However, for whatever reason, the tracks don't end up in my plays history on my Last.FM profile.

**Comment by hugovk** [comment]
This is a problem at Last.fm:

> We are currently experiencing difficulties and as such some users may have problems scrobbling to their profile. We apologise for any inconvenience caused by this; our engineers are working on this. Posted about 2 days ago by jon

http://status.last.fm/

**Comment by stephanebruckert** [comment]
Hi @brlo1973,

That last patch release (1.2.3) should fix any scrobbling issues: https://github.com/stephanebruckert/ShazamScrobbler/releases

 Thanks for the report!
