### ISSUE TITLE
Unable to Scrobble Tracks to Last.FM

### ISSUE THREAD

**Issue by daniel-schulz-codes** [stephanebruckert/ShazamScrobbler#33]
Hey, 

I've been experiencing troubles scrobbling Tracks to Last.FM. I think that this might happen due to changes in the Last.fm API.

Inside the function

```objective-c
- (NSOperation *)performApiCallForMethod:(NSString*)method
                                useCache:(BOOL)useCache
                              withParams:(NSDictionary *)params
                               rootXpath:(NSString *)rootXpath
                        returnDictionary:(BOOL)returnDictionary
                           mappingObject:(NSDictionary *)mappingObject
                          successHandler:(LastFmReturnBlockWithObject)successHandler
                          failureHandler:(LastFmReturnBlockWithError)failureHandler {
```

an example postCall to the Last.FM API looks like:

```bash
curl -X POST -H "Accept: application/json" -H "Cache-Control: no-cache" -H "Postman-Token: da56adfd-0553-0ac7-7da6-512738e91be2" -H "Content-Type: application/x-www-form-urlencoded" -d '' "https://ws.audioscrobbler.com/2.0/?album=&api_key=4cf8b0679f46df8d758b2561bfe1df74&artist=Magic!&duration=-187&method=track.scrobble&sk=*removedThisAccessToken*&timestamp=1485257969&track=Rude&username=takethefake&api_sig=17fcd67e6fde705f830369e70d141b54"
```
*notice: removed my sk from the request above*

this looks legit to the API but the answer is the following:

```xml
<?xml version="1.0" encoding="utf-8"?>
<lfm status="ok">
    <scrobbles ignored="1" accepted="0">
        <scrobble>
            <track corrected="0">Rude</track>
            <artist corrected="0">Magic!</artist>
            <album corrected="0"></album>
            <albumArtist corrected="0"></albumArtist>
            <timestamp>1485257969</timestamp>
            <ignoredMessage code="1"></ignoredMessage>
        </scrobble>
    </scrobbles>
</lfm>
```

as I searched the Last.FM Docs why this error occurs I came up with [Filtered Request](http://www.last.fm/de/api/scrobbling#filtered-requests) and that the ignoredMessageCode leads to errors with the Artist. I experienced the same Error with different Tracks of different Artists. 

I'm not sure how to we can fix this.

**Comment by stephanebruckert** [comment]
Thanks for your report, it's very useful. I can reproduce it, which means I can start working on a fix.

**Comment by daniel-schulz-codes** [comment]
If I can help you in any way, just mention how.

**Comment by stephanebruckert** [comment]
The issue was that in most cases, I was scrobbling songs with a duration of less than 30 seconds, which Last.fm does not accept.

I've just released a patch release: https://github.com/stephanebruckert/ShazamScrobbler/releases

Thanks for the nice report!
