### ISSUE TITLE
iOS Version

### ISSUE THREAD

**Issue by lucasdidthis** [stephanebruckert/ShazamScrobbler#35]
Hej!

How about a version for iOS? 
I'm using an iPad when I'm listening to Vinyl (to browse my catalogue with Discogs and decide what to listen to next). And I would love to use the iPad to scrobble the playing vinyl.

Greetings

PS.: Windows 10 Version would be awesome, too...

**Comment by stephanebruckert** [comment]
Hey @lucasdidthis, 

Sorry for the late response. Unfortunately ShazamScrobbler would not work on iOS as apps are sandboxed, which means one app cannot access other apps data, for security reasons.

It would certainly be feasible on Windows 10, but we would need some developer support https://github.com/stephanebruckert/ShazamScrobbler/issues/29. 

Thanks for your question, best!
