### ISSUE TITLE
The scrobbler could not find the Shazam library. Please make sure Shazam found at least one song and restart the scrobbler.

### ISSUE THREAD

**Issue by silversonicaxel** [stephanebruckert/ShazamScrobbler#36]
This message appears when launched. Any song is detected.

**Comment by stephanebruckert** [comment]
@silversonicaxel sorry just saw your post. Do you still have this issue?

This can happen if the official Shazam app hasn't detected any song yet, or if the Shazam DB file cannot be found.

For the later, I would need more info: 
 - please share your Shazam, ShazamScrobbler and macOS versions,
 - can you check if you have a `ShazamDataModel.sqlite-wal` file at `~/Library/Group\ Containers/4GWDBCF5A4.group.com.shazam/com.shazam.mac.Shazam`

       ✗ ls -l ~/Library/Group\ Containers/4GWDBCF5A4.group.com.shazam/com.shazam.mac.Shazam 
       total 29200
       -rw-r--r--@ 1 stephane 939931750  14381056 30 May 22:39 ShazamDataModel.sqlite
       -rw-r--r--@ 1 stephane 939931750     32768 31 May 01:33 ShazamDataModel.sqlite-shm
       -rw-r--r--@ 1 stephane 939931750     94792 31 May 01:33 ShazamDataModel.sqlite-wal
