### ISSUE TITLE
Can't Make Last.FM Session

### ISSUE THREAD

**Issue by ColoradoBills** [stephanebruckert/ShazamScrobbler#39]
I am running MacOS Monterey 12.1 and I am unable to log into Last.FM via the Shazam Scrobbler. See attached photo for the error. I have verified my username and password are correct. 

<img width="299" alt="Screen Shot 2021-11-23 at 10 40 37 AM" src="https://user-images.githubusercontent.com/63935388/143076640-9c70cd12-4de1-498b-9154-620060e9d180.png">
.

**Comment by stephanebruckert** [comment]
Interesting, was it working for you before Monterey?

**Comment by ColoradoBills** [comment]
The only change is I went from an Intel MacBook to a M1 MacBook. I just  did an update of the program and same issue persists.

**Comment by stephanebruckert** [comment]
> The only change is I went from an Intel MacBook to a M1 MacBook

What was the version of macOS on the Intel MacBook?

**Comment by ColoradoBills** [comment]
Monterey 12.2, same as it is on the M1 MacBook.

**Comment by stephanebruckert** [comment]
I have just released a new version 1.3.0 https://github.com/ShazamScrobbler/shazamscrobbler-macos/releases/tag/1.3.0

It won't fix your issue, but will show a better error message rather than a static one.

Can you please try it and let me know what error message you get back? Thanks!

**Comment by hugo9464** [comment]
Hi @ColoradoBills ,

I am also running MacOS Monterey on an M1 Macbook and I can properly log in to my last.fm account.

According to your screenshots it looks like you have spaces before your Username.

Did you try to log in without those spaces ?

**Comment by ColoradoBills** [comment]
@hugo9464, Good catch. Strange how the migration from the Intel MacBook to the M1 MacBook via iCloud would have made a change in the saved username and password. What's even stranger is how I can't edit the username to  be without spaces. If I delete the spaces, iCloud won't allow me to hit save. If I put at least one space in the username, I can save the change. 

Again, good catch and by manually entering the username I am able to complete the login process.
