### ISSUE TITLE
Auto-Shazam question

### ISSUE THREAD

**Issue by allen-liaoo** [stephanebruckert/ShazamScrobbler#42]
I don't know where to ask this question since I can't find anything about auto-shazam on mac online besides the mac support page, which isn't helpful. But I'm wondering if there is a way to turn on auto-shazam on mac and have this app work with shazam?

**Comment by stephanebruckert** [comment]
Yes if you double-click the logo it will auto-shazam

<img width="269" alt="Screenshot 2023-12-20 at 18 50 25" src="https://github.com/ShazamScrobbler/macos-app/assets/1932338/afeb2e0b-c8a1-4447-a93b-6fb8580c74fd">


<img width="256" alt="Screenshot 2023-12-20 at 18 49 18" src="https://github.com/ShazamScrobbler/macos-app/assets/1932338/9e46bd91-2479-48ac-b1d2-0112ebfd4a6d">
