### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by sethcohn** [stephanebruckert/ShazamScrobbler#5]
No longer builds in 10.10
(it would be really nice if a binary was provided... just saying.)

**Comment by stephanebruckert** [comment]
It's in development. I'm starting to have more time now and I will look into releasing a proper binary very soon. Also it does build in 10.10, make sure you opened the project using the .xcworkspace and not the .xcodeproj.

**Comment by stephanebruckert** [comment]
I have just released a first version. You will find a binary [in the release section](https://github.com/stephanebruckert/ShazamScrobbler/releases).
I am waiting for your feedbacks, thank you!
