### ISSUE TITLE
Delete a scrobble

### ISSUE THREAD

**Issue by stephanebruckert** [stephanebruckert/ShazamScrobbler#7]

**Comment by jowie** [comment]
I would recommend against this. The website already provide a decent way for users to remove unwanted scrobbles. The purpose of this app is a simple one, it would be good not to bog it down with unnecessary extra utilities.

**Comment by stephanebruckert** [comment]
That's true, that was my initial thought. Thanks for the recommendation.

May I know what you think of the [enable/disable feature](https://github.com/stephanebruckert/ShazamScrobbler/issues/17) then? I'm asking this because it is somewhat linked to the "remove scrobble" feature, since a list of "unscrobbled songs" will have to be implemented. 
(Currently, ShazamScrobbler scrobbles _every_ songs detected by Shazam and the only way to not scrobble is to disable Shazam. Are you happy with that and do you find it reasonable?)
